language: objective-c
osx_image: xcode7.3
rvm: system
install:
  # Travis comes with Postgres 9.4 data, so we much clear it out
  - rm -rf /usr/local/var/postgres

  # We are testing installation of homebrew, so should uninstall everything (except xquartz)
  - brew cask list | grep -v xquartz| xargs -t -I % bash -c 'brew cask zap %'
  - brew list | xargs -t -I % bash -c 'brew uninstall --force %'
  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

  - rvm implode --force # We are testing installation of Rubies, so should uninstall everything
  - sudo rm -rf /Users/travis/.vim # Gets in the way of sprout-vim::config recipe
script:
  - ./sprout exec rake ci
