language: objective-c
rvm: system
install:
  - sudo gem install bundler --no-ri --no-rdoc
  - sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future bundle install
  - sudo rm -rf /Users/travis/.vim # Gets in the way of sprout-vim::config recipe
script:
  - bundle exec rake ci
