name             'sprout-vim'
maintainer       'Pivotal'
maintainer_email 'sprout-maintainers@pivotallabs.com'
license          'MIT'
description      'Cookbok for managing vim on an OS X workstation'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.0'
supports         'mac_os_x'
depends          'sprout-base'
depends          'sprout-osx-apps'
depends          'homebrew'
